# Generated by Django 2.2.15 on 2020-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_userpostweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tagssss', to='Posts.Tag'),
        ),
    ]
